name: deploy

on:
  push:
    branches: [master]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Set Up git
        run: |
          git config --local user.email "pr0gr4mm3r-fa1c0n.github.io@noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull

      - name : Install Deps
        run : npm install .

      - name : build
        run : npm run build
      
      - name: Set Up git
        run: |
          git add .
          git commit -m "Update website to recent changes"
          git push -u origin gh-pages
